name: Slack Events API
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hello world data
    defaultValue: slack_messages
    required: true
  - name: SLACK_BOT_TOKEN
    inputType: Secret
    description: ''
    defaultValue: internal_slack_bot_token
    required: false
  - name: SLACK_APP_TOKEN
    inputType: Secret
    description: ''
    defaultValue: internal_slack_app_token
    required: false
  - name: token_messages
    inputType: OutputTopic
    description: ''
    defaultValue: token_messages
    required: false
  - name: gmail_username
    inputType: FreeText
    description: ''
    defaultValue: steve@quix.io
    required: false
  - name: gmail_password
    inputType: Secret
    description: ''
    defaultValue: gmail_password
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
