name: LogSource
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: deployment_logs
    required: true
  - name: token
    inputType: Secret
    description: ''
    defaultValue: quix_api_token
    required: false
  - name: deployment_id
    inputType: FreeText
    description: ''
    defaultValue: daff9f81-8d8a-4ae8-bb48-3676fb4e05e8
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-source
