name: SlackListener
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: slack_users
    required: true
  - name: slack_bot_token
    inputType: Secret
    description: ''
    defaultValue: slack_bot_token
    required: true
  - name: slack_app_token
    inputType: Secret
    description: ''
    defaultValue: internal_slack_app_token
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
