name: Slack Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: alerts_to_send
    required: true
  - name: webhook_url
    inputType: FreeText
    description: The webhook url to send notifications to
    defaultValue: https://hooks.slack.com/services/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
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: slack-destination
